export type User = {
    socket: any,
    name: string,
    isSpectating: boolean,
}

export type Board = {
    a: {},
    b: {},
    c: {},
    d: {},
    e: {},
    f: {},
    g: {},
    h: {},
    i: {},
    j: {},
}

export enum ShipTile {
    EMPTY = "EMPTY",
    EMPTY_HIT = "EMPTY_HIT",
    FULL_PRISTINE = "FULL_PRISTINE",
    FULL_HIT = "FULL_HIT"
}

export enum HitTile {
    EMPTY = "EMPTY",
    HIT = "HIT",
    MISS = "MISS"
}

export type GameState = {
    playerOneReady: boolean,
    playerTwoReady: boolean,
    winner: string,
    playOneShipBoard: Board,
    playTwoShipBoard: Board,
    playOneHitBoard: Board,
    playTwoHitBoard: Board,
}

export type Room = {
    id: string,
    playerOne: any,
    playerTwo: any,
    users: User[],
    gameState: GameState,
}

export const emptyShipBoard: Board = {
    a: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    b: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    c: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    d: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    e: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    f: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    g: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    h: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    i: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    j: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
}

export const emptyHitBoard: Board = {
    a: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    b: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    c: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    d: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    e: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    f: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    g: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    h: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    i: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    j: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
}

export const initialGameState: GameState = {
    playerOneReady: false,
    playerTwoReady: false,
    winner: null,
    playOneShipBoard: emptyShipBoard,
    playTwoShipBoard: emptyShipBoard,
    playOneHitBoard: emptyHitBoard,
    playTwoHitBoard: emptyHitBoard,
}
