export type User = {
    id: string,
    username: string,
    socket: any,
}

export type NewUser = {
    username: string,
    roomId: string,
    roomName: string,
    isSpectating: boolean,
}

export type Room = {
    id: string,
    name: string,
    playerOne: User,
    playerTwo: User,
    spectators: User[],
    gameState: GameState,
}

export type GameState = {
    playerOneReady: boolean,
    playerTwoReady: boolean,
    winner: string,
    playOneShipBoard: Board,
    playTwoShipBoard: Board,
    playOneHitBoard: Board,
    playTwoHitBoard: Board,
}

export type Board = {
    1: {},
    2: {},
    3: {},
    4: {},
    5: {},
    6: {},
    7: {},
    8: {},
    9: {},
    10: {},
}

export enum ShipTile {
    EMPTY = "EMPTY",
    EMPTY_HIT = "EMPTY_HIT",
    FULL_PRISTINE = "FULL_PRISTINE",
    FULL_HIT = "FULL_HIT"
}

export enum HitTile {
    EMPTY = "EMPTY",
    HIT = "HIT",
    MISS = "MISS"
}



export const emptyShipBoard: Board = {
    1: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    2: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    3: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    4: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    5: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    6: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    7: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    8: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    9: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
    10: {1: ShipTile.EMPTY,
        2: ShipTile.EMPTY,
        3: ShipTile.EMPTY,
        4: ShipTile.EMPTY,
        5: ShipTile.EMPTY,
        6: ShipTile.EMPTY,
        7: ShipTile.EMPTY,
        8: ShipTile.EMPTY,
        9: ShipTile.EMPTY,
        10: ShipTile.EMPTY
    },
}

export const emptyHitBoard: Board = {
    1: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    2: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    3: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    4: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    5: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    6: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    7: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    8: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    9: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
    10: {1: HitTile.EMPTY,
        2: HitTile.EMPTY,
        3: HitTile.EMPTY,
        4: HitTile.EMPTY,
        5: HitTile.EMPTY,
        6: HitTile.EMPTY,
        7: HitTile.EMPTY,
        8: HitTile.EMPTY,
        9: HitTile.EMPTY,
        10: HitTile.EMPTY
    },
}

export const initialGameState: GameState = {
    playerOneReady: false,
    playerTwoReady: false,
    winner: null,
    playOneShipBoard: emptyShipBoard,
    playTwoShipBoard: emptyShipBoard,
    playOneHitBoard: emptyHitBoard,
    playTwoHitBoard: emptyHitBoard,
}
